In [1]:
import numpy as np


In [34]:
np_array= np.array([[10,20,30],[20,30,40]])
np_array2=np.array([1,2,3,4])
np_array3=np.array([1,2,3])
np_array4=np.array([[1,2],[3,4]])

In [35]:
np_array.ndim   #kaç size olduğunu 

2

In [36]:
np_array.shape #boyutunu verir

(2, 3)

In [37]:

np_array2

array([1, 2, 3, 4])

In [38]:
np_array

array([[10, 20, 30],
       [20, 30, 40]])

In [39]:
np_array+np_array2

ValueError: operands could not be broadcast together with shapes (2,3) (4,) 

In [40]:
np_array+np_array3

array([[11, 22, 33],
       [21, 32, 43]])

In [41]:
np_array+np_array4

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [42]:
np_array3.shape

(3,)

In [43]:
np_array5 =([[1,2,3],[4,5,6]])

In [44]:
np_array+np_array5

array([[11, 22, 33],
       [24, 35, 46]])

In [45]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr[1, 1, 0])

7


In [46]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])


In [51]:
arr[2:5]

array([20, 25, 30])

In [54]:
#dot product

In [66]:
first_matrix=np.array([[10,20,30]])

In [67]:
first_matrix.shape

(1, 3)

In [68]:
second_matrix=np.array([[1,2],[4,5]])

In [69]:
second_matrix.shape

(2, 2)

In [71]:
first_matrix*second_matrix

ValueError: operands could not be broadcast together with shapes (1,3) (2,2) 

In [72]:
first_matrix.dot(second_matrix)

ValueError: shapes (1,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [73]:
third_matrix=np.array([[1,2],[3,4],[5,6]])

In [74]:
third_matrix.shape

(3, 2)

In [75]:
first_matrix.dot(third_matrix)

array([[220, 280]])