In [1]:
import numpy as np

In [2]:
my_list=[10,20,30,40]

In [5]:
data=np.array(my_list)

In [6]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [7]:
np.random.random(5)

array([0.36497586, 0.38370967, 0.79645505, 0.64143033, 0.21970986])

In [8]:
#array arithmetic

In [9]:
my_list1=[1,2]

In [10]:
my_list2=[2,3]

In [11]:
my_list1+my_list2

[1, 2, 2, 3]

In [12]:
my_numpy_array1=np.array(my_list1)

In [13]:
my_numpy_array2=np.array(my_list2)

In [14]:
my_numpy_array1+my_numpy_array2

array([3, 5])

In [15]:
#arange  & indexing

In [17]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [19]:
np_array=np.arange(0,10)

In [21]:
np_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np_array[0]

0

In [23]:
np_array[-1]

9

In [24]:
np_array[1:4:]

array([1, 2, 3])

In [25]:
np_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])